project_id = "ohftsqsxymtrclnpadam"

[functions.create-booking]
verify_jwt = false

[functions.create-asaas-account]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.check-expired-bookings]
verify_jwt = false

[functions.notification-worker]
verify_jwt = false

[functions.auto-complete-lessons]
verify_jwt = false

